version: "3.8"
services:
  db:
    image: postgres:13
    env_file:
      - task_manager/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    env_file:
      - task_manager/.env
    volumes:
      - $PWD:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin
volumes:
  postgres_data:

